### ISSUE TITLE
logging out

### ISSUE THREAD

**Issue by robb1e** [ciaranj/connect-auth#5]
Hi, noticing some issues with the logging out example.  After logging out, I still seem to be logged in.  Steps to recreate:

goto /, see message 'unauthenticated'
goto /auth/basic, see login prompt, login, see authenticated message
goto /, see message 'authenticated'
goto /logout, get redirected to /, see unauthenticated message
goto /auth/basic, see authenticated message
goto /, see authenticated message

Robbie

**Comment by ciaranj** [comment]
Ah ;) Thats because the http authentications aren't using nonces currently, so the browser just re-authenticates with the server automicaly with the HTTP headers.. I do keep meaning to look at this...

**Comment by robb1e** [comment]
Is there anything I can do to help with that? Interested in using basic auth for a web app I'm developing.

**Comment by ciaranj** [comment]
Sure, (please patches are greatfully received) .. I've just had a look at http://tools.ietf.org/html/rfc2617#section-4.3 ...and I'm not actually sure how (with basic) one tells the browser to stop sending up the auth credentials... but yeah any input appreciated :)

**Comment by ciaranj** [comment]
I've looked into this a bit now, I think this behaviour is, bluntly a 'feature' of Basic (and possibly digest) authentication, you could implement your own logout by (after calling 'logout') you send down a 401 header, but I'm not sure how to do it cleanly (i.e. to also present a redirect)

It would probably be worth looking at a forms-based approach  ( take a look at http://wiki.github.com/ciaranj/connect-auth/creating-a-form-based-strategy for a good starting point) to avoid browser problems/features like this :) ... alternatively consider using one of the provided 3rd party strategies such as the twitter or facebook strategies to do this securely (unless you're behind https basic,digest, forms etc. will never be secure! )

**Comment by robb1e** [comment]
Perhaps it might be worth looking at session + basic auth?

Thing is I'm building out an internal application and eventually I'd like to hook it up to our internal LDAP.  So while I could integrate with Twitter, it's not going to help me in the long run.

Thanks, I'll look into the wiki page you posted and have a think about session based auth.

Robbie

**Comment by ciaranj** [comment]
The issue is that the browser will always post up credentials that have previously been successful for a given _realm_, so to 'logout' from basic auth one needs to present a 'new' realm to the browser client.  Obviously this realm has to be session/client specific or changing it globally would log everyone out so would require at least some notion of session (perhaps just stored as a cookie value).  
The neatest way to solve this framework wise is to  provide a reference to the winning strategy when an authentication occurs somewhere (something I've always intended to do) and allow strategies to declare logout behaviour that occurs whenever a valid scoped logout occurs against this winning strategy, this could then alter then 'realm' that would be presented to the browser when it attempts to access a 'secure' page later, this is all do-able ;)
